@jupyter-widgets/jupyterlab-manager
@bokeh/jupyterlab_bokeh
@finos/perspective-jupyterlab
@jupyter-voila/jupyterlab-preview
@jupyter-widgets/jupyterlab-sidecar
@jupyterlab/celltags
@jupyterlab/geojson-extension
@jupyterlab/git
@jupyterlab/github
@jupyterlab/plotly
@jupyterlab/toc
@lckr/jupyterlab_variableinspector
@mohirio/jupyterlab-horizon-theme
@parente/jupyterlab-quickopen
@pyviz/jupyterlab_pyviz
@ryantam626/jupyterlab_sublime
@telamonian/theme-darcula
bqplot
dask-labextension
ipyannotate
ipycanvas
ipydagred3
ipyevents
ipylab
ipysheet
ipysigma
ipytree
ipyvolume
jupyter-cytoscape
jupyter-fs
jupyter-leaflet
jupyter-materialui
jupyter-matplotlib
jupyter-threejs
jupyter-webrtc
jupyter-widget-datetime
jupyter-vue
jupyter-vuetify
jupyterlab-chart-editor
jupyterlab-dash
jupyterlab-datawidgets
jupyterlab-drawio
jupyterlab-execute-time
jupyterlab-favorites
jupyterlab-jupytext
jupyterlab-kernelspy
jupyterlab-python-bytecode
jupyterlab-python-file
jupyterlab-spreadsheet
jupyterlab-supersave
jupyterlab-system-monitor
jupyterlab-theme-toggle
jupyterlab-topbar-extension
jupyterlab_commands
jupyterlab_email
jupyterlab_filetree
jupyterlab_iframe
jupyterlab_templates
jupyterlab_tensorboard
lineup_widget
nbdime-jupyterlab
plotlywidget
qgrid
